runtime: python37
entrypoint: ~/.local/bin/gunicorn -b :8080 server:app

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto