"""profile table

Revision ID: 55efdbc82f0f
Revises: 5167266f8c49
Create Date: 2020-04-10 08:22:51.981053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55efdbc82f0f'
down_revision = '5167266f8c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_timestamp'), 'profile', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_timestamp'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
